/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.example.math.ValueCalculator;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.List;
import java.util.Arrays;

class ValueCalculatorTest {

    @Test
    void testCalculateValues() {
        // Arrange
        ValueCalculator calculator = new ValueCalculator();
        int a = 3;
        int b = 4;

        // Act
        List<Integer> result = calculator.calculateValues(a, b);

        // Assert
        List<Integer> expected = Arrays.asList(a + 2 * b, 2 * a + b); // [11, 10]
        assertEquals(expected, result);
    }
}

