/*
 * This source file was generated by the Gradle 'init' task
 */
package com.calci;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class ValueCalculatorTest {
    @Test
    void testCalculateValues() {
        // Arrange
        ValueCalculator calculator = new ValueCalculator();
        int a = 3;
        int b = 4;

        // Act
        List<Integer> result = calculator.calculateValues(a, b);

        // Assert
        List<Integer> expected = Arrays.asList(a + 2 * b, 2 * a + b); // [11, 10]
        assertEquals(expected, result);
    }

}
